name: deployment

on: 
 push:
   branches:
     - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: setup nodeJS
      uses: actions/setup-node@v2
      with: 
        node-version : 20

    - name: installing the neccessary packages
      run: |
       cd frontend
       npm install
    - name: building the frontend
      run: npm run build


  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup nodeJS
        uses: actions/setup-node@v2
        with: 
          node-version : 20
      - name: changing the backend
        run: |
          cd backend
          npm install

      - name: building the backend
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build-frontend
      - build-backend
    steps:

      - name: starting the frontend
        run:  | 
          cd frontend
          npm start
      - name: starting the backend
        run:  |
          cd backend
          npm start

