name: deployment

on: 
 push:
   branches:
     - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    # services:
    #   db:
    #     image: mysql:8
    #     env:
    #       MYSQL_USER : 
    #       MYSQL_PASSWORD: 
    #       MYSQL_DATABASE : 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: setup nodeJS
      uses: actions/setup-node@v2
      with: 
        node-version : 20
    - name: installing the neccessary packages
      working-directory: ./frontend
      run: |
        npm install
        npm run build


  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup nodeJS
        uses: actions/setup-node@v2
        with: 
          node-version : 20
      - name: installing the neccessary packages
        working-directory: ./backend
        run: |
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build-frontend
      - build-backend
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # to run frontend we need backend to be running
      - name: changing to backend
        working-directory: ./backend
        run:  npm start
      - name: starting the frontend
        working-directory: ./frontend
        run:  npm start

